MODEL:
  ARCH: BaseAttributeClassifier
  BACKBONE: /shared-data5/guy/modelzoo/clip/ViT-L-14.pt # /shared-data5/guy/modelzoo/clip/ViT-B-16.pt
TRAIN:
  INPUT_SIZE: 224
DATA:
  ROOT_DIR: /shared-data5/guy/data/CUB/CUB_200_2011
#  ANNOTATIONS_FILE: files/annotations/ANET/activity_net_1_3.json
  PATH_TO_CLASSNAMES: files/classnames/CUB/opensets/full/unseen.txt
#  SPLIT_OF_FILENAMES: files/filenames/ANET/openset1/    # test.txt
DATA_LOADER:
  NUM_WORKERS: 16
OPENSET:
  ATTRIBUTES_FILE: files/descriptors/CUB/cub_gpt3_text-davinci-003_descriptions_col_prompt_prefix2.json
  DETECTION_THRESHOLD: 0.17
  MAX_NUM_INTERVALS: 10
TEST:
  DATASET: "CUB"
  SUBSET: "test"
  BATCH_SIZE: 320
  TASKS: ["mAP"]
  NUM_DEMO_PLOTS: 20
OUTPUT_DIR: /shared-data5/ethan_baron/exps/grounding_logs
