MODEL:
  ARCH: FineTunedAttributeClassifier
  BACKBONE: None #/shared-data5/ethan_baron/experiments/clip_training/Dogs orginal prompt new class split/checkpoints/epoch_100.pt #/shared-data5/ethan_baron/experiments/clip_training/Dogs oxford prompt new class split, lr=1e-4, wd=0.0/checkpoints/epoch_100.pt #/shared-data5/ethan_baron/experiments/clip_training/2024_01_18-12_21_56-model_ViT-L-14-lr_0.0001-b_64-j_8-p_amp/checkpoints/epoch_100.pt
  MODEL_SIZE: convnext_base
TRAIN:
  INPUT_SIZE: 224
DATA:
  ROOT_DIR: /shared-data5/guy/data/Dogs120
#  ANNOTATIONS_FILE: files/annotations/ANET/activity_net_1_3.json
  PATH_TO_CLASSNAMES: files/classnames/Dogs120/dogs120.txt
#  SPLIT_OF_FILENAMES: files/filenames/ANET/openset1/    # test.txt
DATA_LOADER:
  NUM_WORKERS: 16
OPENSET:
  ATTRIBUTES_FILE: files/clip_training_data/Dogs120/different_class_split_oxford_prompts/descriptions_for_real_zs.json #files/clip_training_data/Dogs120/complicated_prompts/descriptions_for_real_zs.json #files/clip_training_data/Dogs120/different_class_split_ethan_prompts/descriptions_for_real_zs.json #files/clip_training_data/Dogs120/different_class_split_ethan_prompts/descriptions_for_real_zs.json
  DETECTION_THRESHOLD: 0.17
  MAX_NUM_INTERVALS: 10
TEST:
  DATASET: "Dogs120"
  SUBSET: "test"
  BATCH_SIZE: 64 #16
  TASKS: ["mAP"]
  NUM_DEMO_PLOTS: 30
OUTPUT_DIR: tmp # /shared-data5/brian/exps/grounding_logs #/shared-data5/guy/exps/grounding_logs
SAVE_RESULTS_EVERY: 100000
