MODEL:
  ARCH: FineTunedAttributeClassifier
  BACKBONE: openai
  MODEL_SIZE: ViT-L/14
TRAIN:
  INPUT_SIZE: 224
DATA:
  ROOT_DIR: /shared-data5/guy/data/CAR196
#  ANNOTATIONS_FILE: files/annotations/ANET/activity_net_1_3.json
  PATH_TO_CLASSNAMES: files/classnames/Cars196/cars196.txt
#  SPLIT_OF_FILENAMES: files/filenames/ANET/openset1/    # test.txt
DATA_LOADER:
  NUM_WORKERS: 16
OPENSET:
  ATTRIBUTES_FILE: files/descriptors/Cars196/cars196_gpt3_text-davinci-003_descriptions_col.json
  DETECTION_THRESHOLD: 0.17
  MAX_NUM_INTERVALS: 10
TEST:
  DATASET: "Cars196"
  SUBSET: "train"
  BATCH_SIZE: 128
  TASKS: ["mAP"]
  NUM_DEMO_PLOTS: 5
OUTPUT_DIR: tmp3