MODEL:
  ARCH: FineTunedAttributeClassifier
  BACKBONE: None
  MODEL_SIZE: ViT-B/16
TRAIN:
  INPUT_SIZE: 224
DATA:
  ROOT_DIR: /shared-data5/guy/data
#  ANNOTATIONS_FILE: files/annotations/ANET/activity_net_1_3.json
  PATH_TO_CLASSNAMES: files/classnames/Food101/all.txt
#  SPLIT_OF_FILENAMES: files/filenames/ANET/openset1/    # test.txt
DATA_LOADER:
  NUM_WORKERS: 8
OPENSET:
  # that is the general file for desctiptions by CLASS
  # there are no example information in that file
  ATTRIBUTES_FILE: files/descriptors/Food101/food_gpt3_text-davinci-003_descriptions_ox_noname_filtered.json
  DETECTION_THRESHOLD: 0.17
  MAX_NUM_INTERVALS: 10
TEST:
  DATASET: "food101"
  SUBSET: "test"
  BATCH_SIZE: 128
  TASKS: ["mAP"]
  NUM_DEMO_PLOTS: 5
OUTPUT_DIR: tmp3 # /shared-data5/brian/exps/grounding_logs #/shared-data5/guy/exps/grounding_logs
SAVE_RESULTS_EVERY: 100000
